language: groovy
sudo: false
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.gradle
script: ./travis-build.sh
after_failure:
  - ./travis/publish_reports.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: xvzhl25MxMLLYqDB2YFoODFX/JjltYU3Zdnh8R6YD/Cy1djH+2st0PMs8ERFx+nUQ4RLrtq+r2X2QMMe0bGKPisqz+YwE/TnF4TIm2lbp/k3dfQiNa3HF20m3aQplell3yQhC6wD3hBO53KeGdtZ5Ah2S6oSiM8PRiGcay0UZy0=
  - secure: LEj4RcGVf31S0E45a1SIJJ+nEj05UTVahua0+PCrFyJs4TQAEVIRuclf4HPSJfs9v/xyezEKLPIJadfzSXAMoMY1tEjn5kAeutSESBQSmEy5JEs8cU1Y5Us0EaGdDsfKW3dRnWjBjPzZQAqTCWfX6BCENgU1A/g2N18eUStEk98=
  - secure: U5iBmiD6kBBbYfvInjA7cAmHvLJ8cjAn70lxiihf7abLp8hZ7K1VRRBBc/U96EtTYZP18rKkBZTW0wj9pv2ACEfd3vmZ0hpcq/zAb0Q3ylzXTUbz8NFfpc6/o8vePqFbRjxknRZ47Q7nxlHtHmVxYQcnWhHvfMTS1chO4iGgcoE=
  - secure: d7XgPjAzYR2mBfWMWdh4vWPe+6AhdQ4BLiDK1sAJToEZZF1mpc1eGw+QIxYLwq1S5FNMyAlxqndmB8IxvjO422KKar1sIa6LPbVHVdh2srFFEutLcD+i5B0MDL9luO17T0sXMleB+60JWJg2UscqUfeuvgPCJh+wjiCb9704/Vg=
  - secure: yjrvYcL2KStheccxqoc5qfL2lIplkzGmja7oc5ZyCELelYH6TxP2iCDSE2UvICymlrByAHk5rcoEqhH9vjkRYOQfgXWahT18RkppjFsgc3F0lD1ulhPhunYDaCi0xyyPMddVy8Y9wWbkAyl6MREGKVtKFpkFpJqM0uY+ieUuU1c=
  - secure: g03YHB4AwAMBuTz3L0LCh3pf51Wnnm/noL26ZmHaSvuDbGcZakwIfgclo/7cs16obQXZkbFyj9PqCSeXSHttLBca0cRW+1MU8qTIRhz7zHOzoOEFyxjNRW2Oi9zqpYULFoKNNY95c0JosPnRLdcRbVwmKm6XtqNc6zCGMJ+x79A=
  - secure: Neyw5jWIvdGJunXCszm4hR3IEdHBZoDShDBai8NDjz9ikw9ud54qDa0N+QtUfVDh5IA6r2emH0YhqgsaxInXudEcdByJu21pGAJlhn5GW+AGWIP3a5vtlpD2vAsgWNCuV6MkYheeSN0NgPzNtb8BVqLVWSp1cfPmTuyk234ko8s=
deploy:
  provider: releases
  api_key:
    secure: xRdXMWiKZt6IbMQC2PLjq+EYhNqHuxEMrBKrK7TG0h/C3gdAZP3oH/s//jVr6BqKtbmbPduQTWX5DAy1K2XlvtdEEh0t19JCQSTRMRBRw2LQKoq6sQz8iKD0kspfE4zbywxSLvitbuppj4SPcl55hEQ6PBF0MtWWvVlVZ0dygbk=
  file: build/libs/fields-${TRAVIS_TAG:1}.jar
  on:
    repo: grails-fields-plugin/grails-fields
    tags: true
