language: groovy
sudo: false
jdk:
- openjdk7
cache:
  directories:
  - $HOME/.gradle
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
deploy:
  provider: releases
  api_key:
    secure: RnhIMoSXTyeMwjx4EX/9NAvq9xhDXOgWaKoNHmcRaBYV8F8bPl1ksAfQ36cP7dYpVyj5VeJF5S2syTaQfaRAaXsU3tb/WIVSl/jb5O0u9qhcBdGdzZ8LkVYd7728BvVD6eFclN6mYm6xmwM6jc/nHzxCWsg7qH3snp3CmjbQ8Lo=
  file: build/libs/fields-${TRAVIS_TAG:1}.jar
  on:
    repo: grails-fields-plugin/grails-fields
    branch: grails3
    tags: true
